repository: D491675881/NSD-Navi
repository_url: https://github.com/D491675881/NSD-Navi

message_board_url: http://shimo.im/docs/hTZ0sL4k2ms0avhc

timezone: Asia/Shanghai
lang: zh_CN

title: 内师大专属导航 · NSD-Navi
alias_en: NSD-Navi
alias_cn: 内师大专属导航
description: A Navigation Website for NSD
keywords: 内师大专属导航, NSD-Navi, NSD, BUPT, Navi, Navigation
url: http://shimo.im/docs/hTZ0sL4k2ms0avhc
#url: https://github.com/D491675881/NSD-Navi
#url: http://nsd-navi.com

author: D491675881
#author_url: http://irockbunny.com
#contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-white.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
theme: jekyll-theme-time-machine
